### ISSUE TITLE
Does BMW E60 cluster work?

### ISSUE THREAD

**Issue by Betty1909** [r00li/CarCluster#4]
Can it work with BMW E60 cluster?
I have change to 100kbp and it success to control backlight, but rpm and speed
not work.

And backlight flash again and again.

Thanks!

**Comment by r00li** [comment]
Hello!
Not for now. E series is still in the works. But it is next on my list. I have the cluster already and will start working on it soon-ish. Probably a few weeks. I'll let you know when it's ready.

**Comment by Betty1909** [comment]
Cool,
Thanks for your big work. 😀
Can't wait to playing with it!
![IMG20240313225547](https://github.com/r00li/CarCluster/assets/29305277/0222d5cc-fd16-45a5-96b1-895f0ffb7031)
Here is my cluster, only rpm work. lol

**Comment by r00li** [comment]
Hello! I am happy to report that BMW E60 is now finally supported. Currently the support is still a bit basic, but expect more to come at some point.
